
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mr-robot
 */
public class JSONCreator extends javax.swing.JFrame {

    String str;
    /**
     * Creates new form JSONCreator
     */
    public JSONCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Generate JSON file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Paste the string below to convert into json file");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        str=jTextArea1.getText().toString();
        //System.out.println(str);
        
        // Using replace to replace characters 
      str= str.replaceAll("1. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("2. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("3. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("4. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("5. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("6. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("7. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("8. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("9. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");
      str= str.replaceAll("10. ", "\t\t{ \n" +
        "\t\t\t\"question\": \"");      
      str= str.replaceAll("\na. ", "\",\n\t\t\t\"optionA\": \"");
      str= str.replaceAll("\nb. ", "\",\n\t\t\t\"optionB\": \"");
      str= str.replaceAll("\nc. ", "\",\n\t\t\t\"optionC\": \"");
      str= str.replaceAll("\nd. ", "\",\n\t\t\t\"optionD\": \"");
      str= str.replaceAll("\nFun Fact: ", "\n\t\t\t\"funFactImage\": \" \",\n\t\t\t\"answer\": \" \",\n\t\t\t\"funFact\": \"");
      //str= str+"\n\t\t\t\"funFactImage\": \" \",\n\t\t\t\"answer\": \" \"";
      str= str.replaceAll("\n\n", "\"\n\t\t},\n");

      // Using replace to replace characters 
     // System.out.println(str.replace('e', 'D')); 
     //System.out.println(str+"\"\n\t\t}");
     
     try {
			File file = new File("file.json");
			FileWriter fileWriter = new FileWriter(file);
			fileWriter.write(str+"\"\n\t\t}");
			fileWriter.flush();
			fileWriter.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSONCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSONCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSONCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSONCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSONCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
